"""add_board_id_to_audit_log

Revision ID: 9b6d5afbd0f7
Revises: 29a8a92091e1
Create Date: 2026-07-13 23:33:57.876344

"""
from alembic import op
import sqlalchemy as sa


revision = '9b6d5afbd0f7'
down_revision = '29a8a92091e1'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('board_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'board_id')
    # ### end Alembic commands ###