"""add_indexes

Revision ID: 29a8a92091e1
Revises: 17e6f8a72502
Create Date: 2026-07-13 12:24:45.969603

"""
from alembic import op
import sqlalchemy as sa


revision = '29a8a92091e1'
down_revision = '17e6f8a72502'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_index('idx_board_members_user_id', 'board_members', ['user_id'], unique=False)
    op.create_index('idx_board_members_version', 'board_members', ['version'], unique=False)
    op.create_index('idx_boards_version', 'boards', ['version'], unique=False)
    op.create_index('idx_cards_archived', 'cards', ['is_archived'], unique=False)
    op.create_index('idx_cards_assignee_id', 'cards', ['assignee_id'], unique=False)
    op.create_index('idx_cards_column_id', 'cards', ['column_id'], unique=False)
    op.create_index('idx_cards_deadline', 'cards', ['deadline'], unique=False)
    op.create_index('idx_cards_priority', 'cards', ['priority'], unique=False)
    op.create_index('idx_cards_version', 'cards', ['version'], unique=False)
    op.create_index('idx_columns_version', 'columns', ['version'], unique=False)
    op.create_index('idx_comments_card_id', 'comments', ['card_id'], unique=False)
    op.create_index('idx_comments_version', 'comments', ['version'], unique=False)
    op.create_index('idx_users_version', 'users', ['version'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_version', table_name='users')
    op.drop_index('idx_comments_version', table_name='comments')
    op.drop_index('idx_comments_card_id', table_name='comments')
    op.drop_index('idx_columns_version', table_name='columns')
    op.drop_index('idx_cards_version', table_name='cards')
    op.drop_index('idx_cards_priority', table_name='cards')
    op.drop_index('idx_cards_deadline', table_name='cards')
    op.drop_index('idx_cards_column_id', table_name='cards')
    op.drop_index('idx_cards_assignee_id', table_name='cards')
    op.drop_index('idx_cards_archived', table_name='cards')
    op.drop_index('idx_boards_version', table_name='boards')
    op.drop_index('idx_board_members_version', table_name='board_members')
    op.drop_index('idx_board_members_user_id', table_name='board_members')
    op.drop_index('idx_audit_log_user_id', table_name='audit_log')
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_index('idx_audit_log_created_at', table_name='audit_log')
    op.drop_index('idx_audit_log_action', table_name='audit_log')
    # ### end Alembic commands ###