"""Initial migration

Revision ID: bc3bce564785
Revises: 
Create Date: 2026-07-11 15:09:51.052858

"""
from alembic import op
import sqlalchemy as sa


revision = 'bc3bce564785'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###